export const NEXT_PUBLIC_APP_BASE_URL = process.env.NEXT_PUBLIC_APP_BASE_URL;
export const NEXT_PUBLIC_SERVER_BASE_URL = process.env.NEXT_PUBLIC_SERVER_BASE_URL;
export const NEXT_PUBLIC_PADDLE_CLIENT_TOKEN =
    process.env.NEXT_PUBLIC_PADDLE_CLIENT_TOKEN;
